### ISSUE TITLE
Unexpected token { (import)

### ISSUE THREAD

**Issue by akotlar** [react-monaco-editor/react-monaco-editor#172] opened 2018-12-25 16:00 UTC
with Nextjs 7

nextjs.config.js

```js

webpack(config, options) {
         config.plugins.push(
              new MonacoWebpackPlugin({
                languages: ['json']
              })
            );
          return config;
}

```

```sh
node_modules/monaco-editor/esm/vs/editor/editor.api.js:5
import { PolyfillPromise } from '../base/common/winjs.polyfill.promise.js';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (node_modules/react-monaco-editor/lib/editor.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

/Users/alexkotlar/Dropbox/projects/hail-akotlar/haas/packages/public/node_modules/monaco-editor/esm/vs/editor/editor.api.js:5
import { PolyfillPromise } from '../base/common/winjs.polyfill.promise.js';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (node_modules/react-monaco-editor/lib/editor.js:11:15)

```

**Comment by x5engine** [comment] 2019-01-11 16:33
same error! seems this is using ES7 which is not yet supported by the framework like meteor and next...

any workaround?

**Comment by domoritz** [comment] 2019-01-14 16:31
You can run the code through babel first.

**Comment by x5engine** [comment] 2019-01-14 17:39
why do you mean? can you be more explicit please??

**Comment by domoritz** [comment] 2019-01-15 12:13
I don't know nextjs but babel (https://babeljs.io/) is a transpiler that takes in JS and compiles it to an equivalent version of a different version of JS. For example, it can rewrite imports and compile them to require statements. I think it could help you with the issue you see.

**Comment by x5engine** [comment] 2019-01-21 00:36
I don't even use nextjs so that's why I am asking :)

**Comment by bsell93** [comment] 2019-01-22 17:12
I'm getting this error as well, running create react app jest tests.
The project is pretty bare bones minus the react-monaco-editor package.
Repro:
1. Create app using create react app
2. Add react-monaco-editor
3. Run jest tests

**Comment by x5engine** [comment] 2019-01-31 02:36
monaco failaco

**Comment by sumboxcar182** [comment] 2019-02-04 17:34
I found a workaround for now that allowed me to at least mock out the code editor.

I used this https://jestjs.io/docs/en/manual-mocks.html but i found that all i had to do was create a new folder ```__mocks__ ``` at the same directory as my node modules. Then in that folder i placed a file called ```react-monaco-editor.js``` which just had  the line ```use strict```. You probably don't need that line, but at least as of now i'm able to run unit tests. 

I hope this helps just getting unit tests up and running again.

**Comment by sumboxcar182** [comment] 2019-02-05 15:17
Followup as i found that i was still hitting the issues with storybook. 

I believe the issue is due to how imports are working for this project, as the imports are pointing to the uncompiled, es6 code, which is causing the crash to happen in jest.

I've updated the react-monaco-editor mock to look like this

```
import * as React from 'react';

function MonacoEditor() {
    return (<div />);
}

module.exports.default = MonacoEditor;
```

and this is now no longer crashing the unit tests. 

I think the solution though would be for this project to point to the lib section instead of the src, and that should fix this.

**Comment by domoritz** [comment] 2019-02-05 16:11
We're using the es Version because we can get smaller bundles that only include the required functionality. This is suggested by https://github.com/Microsoft/monaco-editor-webpack-plugin. I wish there was a way around this issue here but I haven't had an idea yet.

**Comment by x5engine** [comment] 2019-02-07 10:04
I gotta do something about this

**Comment by domoritz** [comment] 2019-02-07 16:38
I appreciate all of your understanding and help.

**Comment by sumboxcar182** [comment] 2019-02-08 14:20
@domoritz  i completely understand, and given how big monaco can be i am more in favor of keeping the file size as small as possible. I think the workaround for right now is at least ok, although maybe we could have a umd bundle that is also provided? So for jest tests we can point to that too. Either way though this one is tricky.

**Comment by domoritz** [comment] 2019-02-08 16:28
If someone could update the build process to spit out multiple bundles, that would be sweet.

**Comment by danvoyce** [comment] 2019-07-08 08:33
Has anyone got a fix for this yet? I've tried mocking as per above comments but not working for me.

**Comment by domoritz** [comment] 2019-07-20 16:22
For now, we expect es6 support.

**Closed** 2019-07-20 16:21 UTC

**Comment by zerocewl** [comment] 2020-05-07 08:16
any news or workaround here?

**Comment by sumboxcar182** [comment] 2020-05-12 13:43
Hello! 

Hopping back in, i just saw jest now supports es modules by default as of jest 26, although it's not stable. This might fix that issue, but i haven't had a chance to take a look. I'm hopefully going to get some time in the next couple of weeks to get to jest 26, but until then if anyone makes the bump let me know as it might solve it. 

https://jestjs.io/blog/2020/05/05/jest-26#native-esm-support

**Comment by alexl0gan** [comment] 2021-02-02 15:22
@sumboxcar182 I just tried the update and it did not help.

I'm adding `react-monaco-editor|monaco-editor` to the `transformIgnorePatterns` list. This solves the `cannot use import outside of a module` error but now introduces

```
.../td-console/node_modules/monaco-editor/esm/vs/editor/editor.api.js:20
  const global = self; // Set defaults for standalone editor
        ^

  SyntaxError: Identifier 'global' has already been declared
```
