### ISSUE TITLE
Error: Model is disposed!

### ISSUE THREAD

**Issue by LeeHao92** [react-monaco-editor/react-monaco-editor#206] opened 2019-05-10 11:10 UTC
#### MonacoEditor component file

```js
const Editor = React.lazy(() =>
  import(/* webpackChunkName: "monaco-editor-c" */ 'react-monaco-editor'),
)

// changeCode: dispatch change action
// value: redux store value
<React.Suspense fallback={<Loading />}>
  <Editor value={value} onChange={changeCode} language="java" />
</React.Suspense>
```

multiple fetch same chunk file when I change value.

### console gif

![May-10-2019 19-06-37](https://user-images.githubusercontent.com/22903176/57523149-c1f5bd80-7356-11e9-886c-c9a3588f8ed9.gif)

### console image

![image](https://user-images.githubusercontent.com/22903176/57523232-01240e80-7357-11e9-8bb9-b4abf0accdf6.png)

![image](https://user-images.githubusercontent.com/22903176/57523316-3df00580-7357-11e9-9861-eac6ad23d14f.png)

**Comment by LeeHao92** [comment] 2019-05-10 11:36
React.lazy function should not write in render function.

**Comment by jedmao** [comment] 2019-06-13 19:00
I'm experiencing the same issue and [I am not using `React.lazy`](https://github.com/jedmao/queso/blob/master/src/components/Editor.tsx). See http://queso.surge.sh/attempt and play with the playground and you'll see it crash.

I think this issue should be reopened.

```json
    "react-monaco-editor": "^0.26.2",
```

**Comment by domoritz** [comment] 2019-06-13 20:36
@jedmao Can you show the issue with the example in the repo and send a PR to fix the bug?

**Comment by jedmao** [comment] 2019-06-13 22:02
Unfortunately, I'm not sure how to reproduce the issue, but it shouldn't be closed at least.

**Comment by jedmao** [comment] 2019-06-13 22:03
FWIW, it only happens on my http://queso.surge.sh/attempt page, but not the other ones and I don't see anything particularly special about that function.

**Comment by jedmao** [comment] 2019-06-13 22:08
Actually, it happens the moment I try to type `attempt` on a new line. I can type `attemp` but the moment I hit the `t` it crashes.

**Comment by LeeHao92** [comment] 2019-06-13 22:40
I try to happen in `http://queso.surge.sh/attempt` page, but not throw error. ❓

**Comment by jedmao** [comment] 2019-06-14 20:45
@LeeHao92 you have to type the full word "attempt" to see it crash. The moment you hit the letter <kbd>t</kbd> it crashes. Can you reproduce it like this?

<img width="619" alt="Screen Shot 2019-06-14 at 3 44 07 PM" src="https://user-images.githubusercontent.com/1058243/59537112-4d64f000-8ebb-11e9-98af-e4e6759d57d2.png">

**Comment by LeeHao92** [comment] 2019-06-14 23:43
@jedmao
I don't know why crash.
I reopen this issues.

**Comment by domoritz** [comment] 2019-07-20 16:20
Please provide a small working example. I'm going to close this since the issue seems to be in monaco itself.

**Closed by domoritz** 2019-07-20 16:20 UTC

**Comment by rikeshpatel** [comment] 2019-10-14 18:19
Experienced this while using multiple editor tags on the same page. Resolved by adding keys.
`<MonacoEditor
          key="description-editor"
          ...
/>
`

**Comment by ohenriksson** [comment] 2022-10-27 15:03
Exprienced the same issue in a Angular app with three instances of monaco editor in the same view.
Resolved it by following [rikeshpatel](https://github.com/rikeshpatel) advice to add unique identifiers, I added unique ids.
` <ngx-monaco-editor [id]="editor1" ....`
